from __future__ import annotations

import re

from src.bot import messages as msg


TRAINER_COPY = (
    msg.TRAINER_FEEDBACK_PROMPT,
    msg.TRAINER_AFTER_LINK_HERO,
    msg.TRAINER_LINK_INVALID,
    msg.TRAINER_LINK_TELEGRAM_CONFLICT,
    msg.TRAINER_WELCOME_TRIAL_ACTIVATED,
    msg.TRAINER_ERROR_BOOKING_NOT_FOUND,
    msg.TRAINER_ERROR_CANCEL_FAILED,
    msg.TRAINER_ERROR_FEEDBACK_SAVE_FAILED,
    msg.TRAINER_ERROR_RESPOND_FAILED,
    msg.TRAINER_ERROR_NO_SERVICES,
    msg.TRAINER_REQUEST_BOOK_NO_SLOTS_TWO_WEEKS,
    msg.TRAINER_ERROR_REQUEST_BOOK_PAYLOAD,
    msg.TRAINER_ERROR_SLOT_TAKEN_FOR_REQUEST,
    msg.TRAINER_EDITOR_OPEN_HINT,
    msg.TRAINER_BOOKINGS_OPEN_WEBAPP,
    msg.TRAINER_CLIENTS_OPEN_WEBAPP,
    msg.TRAINER_REQUESTS_OPEN_WEBAPP,
    msg.TRAINER_PASSES_INTRO_WEBAPP,
    msg.TRAINER_INVITE_INTRO_HTML,
    msg.TRAINER_INVITE_ERR_PROFILE_INCOMPLETE,
    msg.TRAINER_SCHEDULE_TITLE,
    msg.TRAINER_SCHEDULE_EMPTY,
    msg.TRAINER_SCHEDULE_OPEN_WEBAPP,
    msg.TRAINER_SCHEDULE_CHOOSE_WEEK,
    msg.TRAINER_SCHEDULE_CHOOSE_DAY,
    msg.TRAINER_SCHEDULE_CHOOSE_TIME,
    msg.TRAINER_SCHEDULE_SELECT_AT_LEAST_ONE,
    msg.TRAINER_SCHEDULE_TEMPLATE_CHOOSE_ANOTHER_DAY,
    msg.TRAINER_REQUESTS_FILTER_LINE,
    msg.TRAINER_REQUESTS_EMPTY,
    msg.TRAINER_REQUESTS_SECTION_NEW,
    msg.TRAINER_REQUEST_DETAIL_RESPONDED_HINT,
    msg.TRAINER_REQUEST_REMIND_SLOTS_SET,
    msg.TRAINER_REQUEST_BOOK_CHOOSE_SLOT,
    msg.TRAINER_REQUEST_REMIND_HAS_SLOTS,
    msg.TRAINER_RESPOND_SUCCESS,
    msg.TRAINER_RESPOND_PROMPT_COMMENT,
    msg.TRAINER_DIGEST_OWED_LINE_CONFIRMS_ONLY,
    msg.TRAINER_DIGEST_MORNING_REC_FIRST_TIMER_OPENS_DAY,
    msg.TRAINER_DIGEST_MORNING_LITE_REC,
    msg.TRAINER_DIGEST_WEEKLY_REC_ALL_GOOD,
    msg.TRAINER_DIGEST_DROUGHT_OPEN_REQUESTS,
    msg.TRAINER_DIGEST_DROUGHT_CATALOG_HIDDEN,
    msg.TRAINER_DIGEST_DROUGHT_NO_SLOTS,
    msg.TRAINER_DIGEST_DROUGHT_DORMANT,
    msg.TRAINER_RELAY_REPLY_PROMPT,
    msg.TRAINER_COLLECTIVE_CLAIM_SUCCESS,
    msg.TRAINER_COLLECTIVE_INVITE_SEATS_FULL,
    msg.TRAINER_SUBSCRIPTION_ACTIVE,
    msg.TRAINER_SUBSCRIPTION_WITHOUT_TIER,
    msg.TRAINER_SUBSCRIPTION_EXPIRED,
    msg.TRAINER_SUBSCRIPTION_JUST_EXPIRED_TRIAL,
    msg.TRAINER_SUBSCRIPTION_JUST_EXPIRED_PAID,
)


def test_selected_trainer_copy_uses_formal_address() -> None:
    informal_words = re.compile(r"\b(?:ты|тебе|тебя|твой|твоя|твою|твоём|твоей|попробуй|открой|добавь|укажи|выбери|напиши|получи)\b", re.IGNORECASE)
    violations = [text for text in TRAINER_COPY if informal_words.search(text)]
    assert not violations, violations
