#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "BY-egress VPS for ledlife/junost (TASK-083, PDEC-004)"

# ── Stage 1: pick and provision the VPS ────────────────────────────────────
stage "Belarusian VPS: sign up and provision"
say "ledlife.by and junost.by geo-block everything that isn't a real Belarusian IP"
say "(X-Forwarded-For spoofing does not help, and spoofing is forbidden by product"
say "rule — DESIGN-INGESTION-PARSERS-V1.md §6.2). This gets you a REAL BY egress"
say "for notification_service's scheduler, never a faked one."
say "PDEC-004 named two providers. Pick one — either is fine, hoster.by is the"
say "cheaper/simpler option, A1 Cloud if you already bank with A1."
step "hoster.by — cheapest BY VPS, sign up and order the smallest VPS plan."
open_url "https://hoster.by/vps"
step "A1 Cloud (alternative) — Belarusian mobile operator's cloud arm."
open_url "https://cloud.a1.by"
say "Either way you need: a running VPS, its public IPv4 address, and SSH access"
say "(root or a sudo user + your public key installed)."
pause "Come back here once the VPS is up and you can SSH into it."
confirm "Can you SSH into the VPS right now from this machine?" || {
  warn "Get SSH working first (paste your ~/.ssh/id_*.pub into the provider's"
  warn "console/rescue mode if needed), then re-run this wizard."
  exit 1
}

# ── Stage 2: capture connection details (not written to any repo file) ────
stage "VPS connection details"
note "These are typed into your local shell for THIS session only — the wizard"
note "never writes SSH details into .env.example or anything git-tracked."
ask BY_VPS_HOST "VPS public IP or hostname:"
ask BY_VPS_SSH_USER "SSH user (e.g. root):"
say "We'll assume default SSH port 22 and your default key unless you say otherwise."
confirm "Non-default SSH port or key?" && {
  ask BY_VPS_SSH_PORT "SSH port:"
  ask BY_VPS_SSH_KEY "Path to private key (e.g. ~/.ssh/id_ed25519):"
} || true
BY_VPS_SSH_PORT="${BY_VPS_SSH_PORT:-22}"
say "Testing SSH reachability..."
if ssh -o BatchMode=yes -o ConnectTimeout=6 -p "$BY_VPS_SSH_PORT" \
     ${BY_VPS_SSH_KEY:+-i "$BY_VPS_SSH_KEY"} \
     "${BY_VPS_SSH_USER}@${BY_VPS_HOST}" "echo ok" >/dev/null 2>&1; then
  printf '  %s✓%s SSH reachable.\n' "$GREEN" "$RESET"
else
  warn "Couldn't SSH in non-interactively (BatchMode). That's OK if you use a"
  warn "passphrase-protected key — you'll just be prompted below."
fi

# ── Stage 3: tunnel — WireGuard primary, SSH -D fallback ──────────────────
stage "Tunnel: route worker traffic through the VPS"
say "Primary path: WireGuard (stable, survives reconnects, low overhead)."
say "Fallback: SSH dynamic port-forward (simpler, but dies if the SSH session drops"
say "— fine to prove the concept, not for unattended production)."
confirm "Set up WireGuard (recommended)? Answer N to see the SSH -D fallback instead." && {
  if command -v wg >/dev/null 2>&1; then
    WG_DIR=$(mktemp -d)
    (umask 077 && wg genkey | tee "$WG_DIR/worker.key" | wg pubkey > "$WG_DIR/worker.pub")
    (umask 077 && wg genkey | tee "$WG_DIR/vps.key" | wg pubkey > "$WG_DIR/vps.pub")
    WORKER_PRIV=$(cat "$WG_DIR/worker.key"); WORKER_PUB=$(cat "$WG_DIR/worker.pub")
    VPS_PRIV=$(cat "$WG_DIR/vps.key"); VPS_PUB=$(cat "$WG_DIR/vps.pub")
    rm -rf "$WG_DIR"
    printf '  %s✓ generated%s a fresh WireGuard keypair for each side.\n' "$GREEN" "$RESET"
  else
    warn "wg (wireguard-tools) isn't installed here. Generating placeholder keys —"
    warn "install wireguard-tools on BOTH sides and run 'wg genkey'/'wg pubkey' for real."
    WORKER_PRIV="<run: wg genkey>"; WORKER_PUB="<run: echo \$WORKER_PRIV | wg pubkey>"
    VPS_PRIV="<run: wg genkey>"; VPS_PUB="<run: echo \$VPS_PRIV | wg pubkey>"
  fi
  say ""
  step "On the VPS (/etc/wireguard/wg0.conf), as root:"
  cat <<EOF

    [Interface]
    Address = 10.83.0.1/24
    PrivateKey = $VPS_PRIV
    ListenPort = 51820

    [Peer]
    PublicKey = $WORKER_PUB
    AllowedIPs = 10.83.0.2/32

EOF
  step "Then: sysctl -w net.ipv4.ip_forward=1  (and persist in /etc/sysctl.conf),"
  step "add an iptables MASQUERADE rule for the VPS's public interface, and"
  step "systemctl enable --now wg-quick@wg0"
  say ""
  step "On the notification_service worker host, /etc/wireguard/wg0.conf:"
  cat <<EOF

    [Interface]
    Address = 10.83.0.2/24
    PrivateKey = $WORKER_PRIV

    [Peer]
    PublicKey = $VPS_PUB
    Endpoint = ${BY_VPS_HOST}:51820
    AllowedIPs = 10.83.0.1/32
    PersistentKeepalive = 25

EOF
  step "Then: systemctl enable --now wg-quick@wg0"
  say ""
  say "Route ONLY the ice-parser HTTP calls through the tunnel (don't tunnel all"
  say "worker traffic) — e.g. a local HTTP proxy on the worker bound to the wg0"
  say "interface, or a per-request SOCKS proxy pointed at the VPS via the tunnel."
  say "The exact proxy binary is up to you (tinyproxy/dante both work); the"
  say "important part is: its listen address is what BY_EGRESS_PROXY_URL points"
  say "at in stage 5."
  pause "Come back here once traffic through 10.83.0.1 reaches the internet."
} || {
  say "SSH -D fallback (dies with the SSH session — fine for a manual proof, not"
  say "for unattended production):"
  step "Run this in a terminal you can leave open:"
  say "    ssh -N -D 1080 -p ${BY_VPS_SSH_PORT} ${BY_VPS_SSH_KEY:+-i $BY_VPS_SSH_KEY} ${BY_VPS_SSH_USER}@${BY_VPS_HOST}"
  say "That opens a SOCKS5 proxy at localhost:1080 tunneled through the VPS."
  pause "Leave that running, then come back here."
}

# ── Stage 4: verify the egress is really Belarusian ────────────────────────
stage "Verify: is the egress really BY?"
say "Don't trust this script blindly — read the raw response yourself below."
ask BY_EGRESS_TEST_PROXY "Proxy URL to test through (e.g. socks5h://127.0.0.1:1080 or http://10.83.0.1:8080):"
say "Querying ipinfo.io through that proxy..."
if command -v curl >/dev/null 2>&1; then
  RESP=$(curl -s --max-time 8 --proxy "$BY_EGRESS_TEST_PROXY" https://ipinfo.io/json || true)
  if [[ -n "$RESP" ]]; then
    printf '\n%s\n\n' "$RESP"
    if grep -q '"country": *"BY"' <<<"$RESP" || grep -q '"country":"BY"' <<<"$RESP"; then
      printf '  %s✓ country code is BY.%s\n' "$GREEN" "$RESET"
    else
      warn "That response does NOT show country=BY. Do not proceed until it does —"
      warn "flip is_enabled on ledlife/junost only once this is genuinely BY."
    fi
  else
    warn "curl through that proxy returned nothing. Check the tunnel is up and the"
    warn "proxy URL/scheme (http:// vs socks5h://) matches what you configured."
  fi
else
  warn "curl not found here — run manually from the worker host:"
  say "    curl --proxy \"$BY_EGRESS_TEST_PROXY\" https://ipinfo.io/json"
fi
confirm "Confirmed BY in the raw response above — proceed?" || {
  warn "Stopping here. Re-run this wizard once the egress genuinely shows BY."
  exit 1
}

# ── Stage 5: wire it into the app config ───────────────────────────────────
stage "Point notification_service at the tunnel"
say "TASK-083 already wired src/shared/config.py + src/ingestion/scheduler.py to"
say "read BY_EGRESS_PROXY_URL: when it's set, IceIngestScheduler treats"
say "requires_by_egress jobs as satisfied (the flag itself is never cleared)."
ask BY_EGRESS_PROXY_URL "Final BY_EGRESS_PROXY_URL for notification_service (e.g. http://10.83.0.1:8080):"
write_env BY_EGRESS_PROXY_URL "$BY_EGRESS_PROXY_URL"
warn "This wrote to your local .env only (gitignored). On a real deploy (Railway"
warn "or wherever notification_service runs), set the SAME variable in that"
warn "environment's own secret/config store — never in .env.example or git."
say ""
say "Registry entries to flip is_enabled=true for, per data/minsk-parser-registry.yaml:"
step "arena_id 5 — ledlife.by (Ледовый дворец спорта Минской области)"
step "arena_id 8 — junost.by (junost_weekend_grid_v1)"
say "Do this via the admin bot's ice_parser_jobs screen if it exists, or a direct"
say "UPDATE against the matching ice_parser_jobs rows — leave requires_by_egress"
say "itself as true, only flip is_enabled."

# ── Stage 6: restart and watch the first real run ──────────────────────────
stage "Restart worker and watch the first run"
step "Restart/redeploy notification_service so it picks up BY_EGRESS_PROXY_URL."
step "Wait for the next scheduled tick (ledlife/junost cadence) or trigger it"
step "manually by setting that job's next_run_at = now() (per the epic's own"
step "'run now' convention — the scheduler never scrapes inline over HTTP)."
step "Check ice_scrape_runs for the new row: status should be ok or empty, NOT"
step "blocked (error_code=requires_by_egress) or error."
pause "Once you've seen a non-blocked run for both jobs, press Enter to finish."

finish
