#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

banner "Stable Cloudflare Tunnel for the local Mini App (no more flaky quick tunnels)"

say "Today's dev tunnel is an anonymous cloudflared quick-tunnel with a"
say "localhost.run SSH fallback — both are ephemeral, both drop randomly, and"
say "every drop rewrites .env and restarts every bot. This wizard replaces that"
say "with a NAMED Cloudflare Tunnel on your own domain: the URL never changes"
say "again, and the tunnel runs as a background OS service, not a tmux window."
say ""
say "(ngrok was considered and rejected: even its free static domains show a"
say "'Visit Site' interstitial page to browser traffic, which would replace"
say "the Mini App with a warning screen inside Telegram's WebView.)"

# ── Stage 1: get a domain into Cloudflare ──────────────────────────────────
stage "Get a domain live in Cloudflare"
confirm "Do you already have a domain live in Cloudflare (Websites tab shows it Active)?" || {
  say "Fastest path: buy a cheap domain directly through Cloudflare Registrar —"
  say "no markup, and it's live in your account immediately (no nameserver wait)."
  open_url "https://dash.cloudflare.com/?to=/:account/domains/register"
  step "Search for something cheap (.xyz/.dev/.cc etc. are usually a few \$/year),"
  step "buy it. It appears under Websites as Active right away."
  note "Alternative: already own a domain elsewhere → add it as a Cloudflare zone"
  note "(free) and repoint nameservers at your registrar — works, but can take"
  note "hours to propagate. Registrar purchase is faster if you don't care which"
  note "domain you use for this dev tunnel."
  pause "Come back here once a domain shows Active in your Cloudflare dashboard."
}
ask DOMAIN "Domain now live in Cloudflare (e.g. example.com):"

# ── Stage 2: cloudflared tunnel login ──────────────────────────────────────
stage "Authorize cloudflared against that domain"
say "This opens a browser, asks you to pick the zone (your domain), and drops a"
say "certificate at ~/.cloudflared/cert.pem that every future cloudflared"
say "command on this machine uses to prove it's allowed to manage tunnels/DNS"
say "for that domain."
if [[ -f "$HOME/.cloudflared/cert.pem" ]]; then
  say "~/.cloudflared/cert.pem already exists — skipping (delete it first if you"
  say "need to re-auth against a different account/zone)."
else
  cloudflared tunnel login
  if [[ ! -f "$HOME/.cloudflared/cert.pem" ]]; then
    warn "~/.cloudflared/cert.pem still missing — the browser auth didn't finish."
    warn "Re-run this wizard once you've completed it."
    exit 1
  fi
  printf '  %s✓%s cert.pem present.\n' "$GREEN" "$RESET"
fi

# ── Stage 3: create the named tunnel ───────────────────────────────────────
stage "Create the named tunnel"
ask TUNNEL_NAME "Tunnel name [trainer-crm-dev]:"
TUNNEL_NAME="${TUNNEL_NAME:-trainer-crm-dev}"
CREATE_OUT="$(cloudflared tunnel create "$TUNNEL_NAME" 2>&1)" || {
  if grep -qi "already exists" <<<"$CREATE_OUT"; then
    warn "a tunnel named '$TUNNEL_NAME' already exists — reusing it."
  else
    printf '%s\n' "$CREATE_OUT"
    warn "cloudflared tunnel create failed. Fix the error above and re-run."
    exit 1
  fi
}
printf '%s\n' "$CREATE_OUT"
TUNNEL_UUID="$(grep -oE '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' <<<"$CREATE_OUT" | head -n1)"
if [[ -z "$TUNNEL_UUID" ]]; then
  TUNNEL_UUID="$(cloudflared tunnel list -o json 2>/dev/null | grep -B2 "\"name\": *\"$TUNNEL_NAME\"" | grep -oE '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' | head -n1 || true)"
fi
if [[ -z "$TUNNEL_UUID" ]]; then
  warn "couldn't parse the tunnel UUID automatically."
  ask TUNNEL_UUID "Paste the tunnel UUID from the output above:"
fi
CRED_FILE="$HOME/.cloudflared/${TUNNEL_UUID}.json"
if [[ ! -f "$CRED_FILE" ]]; then
  warn "expected credentials file not found at $CRED_FILE — check the create"
  warn "output above for the actual path and re-run if it's different."
fi
printf '  %s✓%s tunnel: %s  uuid: %s\n' "$GREEN" "$RESET" "$TUNNEL_NAME" "$TUNNEL_UUID"

# ── Stage 4: route DNS ─────────────────────────────────────────────────────
stage "Point a subdomain at the tunnel"
ask SUBDOMAIN "Subdomain for the dev Mini App [dev]:"
SUBDOMAIN="${SUBDOMAIN:-dev}"
HOSTNAME="${SUBDOMAIN}.${DOMAIN}"
cloudflared tunnel route dns "$TUNNEL_NAME" "$HOSTNAME" || {
  warn "route dns failed — if it says the record already exists, that's fine,"
  warn "continuing."
}
printf '  %s✓%s %s now routes to tunnel %s\n' "$GREEN" "$RESET" "$HOSTNAME" "$TUNNEL_NAME"

# ── Stage 5: write the ingress config ──────────────────────────────────────
stage "Write the ingress config"
CONFIG_PATH="$HOME/.cloudflared/trainer-crm-dev-config.yml"
cat > "$CONFIG_PATH" <<EOF
tunnel: ${TUNNEL_UUID}
credentials-file: ${CRED_FILE}

ingress:
  - hostname: ${HOSTNAME}
    service: http://localhost:8000
  - service: http_status:404
EOF
say "Wrote $CONFIG_PATH:"
say ""
cat "$CONFIG_PATH"
say ""

# ── Stage 6: install as a persistent background service ───────────────────
stage "Install as a background service (survives crashes/reboots)"
say "This is the actual fix for 'tunnel keeps dying': instead of a process in a"
say "tmux window, macOS launchd supervises it forever, restarting it if it dies"
say "and starting it again on every login — nobody has to remember to run it."
say "Needs sudo once, to install the system daemon."
if confirm "Install now via 'sudo cloudflared service install'?"; then
  sudo cloudflared service install --config "$CONFIG_PATH"
  printf '  %s✓%s service installed.\n' "$GREEN" "$RESET"
  note "check status any time:  sudo launchctl list | grep cloudflared"
  note "logs (macOS):           /Library/Logs/com.cloudflare.cloudflared.err.log"
  note "                        /Library/Logs/com.cloudflare.cloudflared.out.log"
else
  SKIPPED+=("cloudflared service install --config $CONFIG_PATH (run manually when ready)")
  warn "skipped — the tunnel will only run when you start it by hand:"
  warn "  cloudflared tunnel run --config $CONFIG_PATH $TUNNEL_NAME"
fi

# ── Stage 7: verify end-to-end, then wire it into the app ──────────────────
stage "Verify and wire into .env"
if curl -sf -m 3 http://localhost:8000/webapp/catalog >/dev/null 2>&1; then
  printf '  %s✓%s local API is up on :8000.\n' "$GREEN" "$RESET"
else
  warn "local API isn't answering on :8000 — run ./dev-start in another terminal,"
  warn "then come back and re-check (the tunnel itself can still be wired below)."
fi
say "Polling https://${HOSTNAME}/webapp/catalog (DNS/tunnel bring-up can take a"
say "few seconds after a fresh service install)..."
STATUS=""
for _ in $(seq 1 15); do
  STATUS="$(curl -s -o /dev/null -w '%{http_code}' -m 5 "https://${HOSTNAME}/webapp/catalog" || true)"
  [[ "$STATUS" == "200" ]] && break
  sleep 2
done
if [[ "$STATUS" == "200" ]]; then
  printf '  %s✓ HTTP 200%s from https://%s\n' "$GREEN" "$RESET" "$HOSTNAME"
else
  warn "got HTTP ${STATUS:-<no response>} from https://${HOSTNAME} — not 200 yet."
  warn "DNS can take a minute to propagate; re-run 'curl -I https://${HOSTNAME}'"
  warn "yourself in a bit. Writing the URL to .env below regardless — it's"
  warn "correct even if propagation is still catching up."
fi

STABLE_URL="https://${HOSTNAME}"
write_env STABLE_TUNNEL_URL "$STABLE_URL"
write_env WEBAPP_BASE_URL "$STABLE_URL"
write_env API_BASE_URL "$STABLE_URL"
note "STABLE_TUNNEL_URL is a marker: a follow-up code change (not part of this"
note "wizard) teaches scripts/dev_tunnel_loop.sh to see it and stop spinning up"
note "ephemeral quick tunnels once it's set. Restart ./dev-start after that"
note "change lands so the bots pick up the new fixed URL."

finish
