"""Minsk, Moscow, and St. Petersburg arenas that have a parser spec.

Slugs and city names are ``arena_profiles.slug`` and ``cities.name`` from the dev
database (read-only SELECT by the spec's arena_id), checked against the arena name.
A fresh database needs these rows before ``build_minsk_job_seeds()`` can bind.
"""

from __future__ import annotations

from sqlalchemy.orm import Session

from src.ingestion.arena_seed import SeedArena, SeedCity, apply_arena_seed

CAPITAL_CITIES: list[SeedCity] = [
    SeedCity("Минск", 0, "BY", "BY_BASE"),
    SeedCity("Москва/МО", 1, "RU", "RU_MOSCOW"),
    SeedCity("Санкт-Петербург/ЛО", 2, "RU", "RU_BASE"),
]

_MSK = "Europe/Minsk"
_MOW = "Europe/Moscow"

ARENAS: list[SeedArena] = [
    SeedArena(
        2,
        "Минск",
        "Минск Арена",
        "Минск, пр-т Победителей, 111",
        53.9394,
        27.4685,
        "manezh",
        True,
        "minskarena_main_saleframe_v1",
        _MSK,
    ),
    SeedArena(
        3,
        "Минск",
        "ТЦ Замок",
        "Минск, пр-т Победителей, 65",
        53.9165,
        27.5478,
        "tts-zamok",
        True,
        "zamok_html_v1",
        _MSK,
    ),
    SeedArena(
        4,
        "Минск",
        "СДЮШОР по фигурному катанию",
        "Минск, пр-т Каролинский, 5",
        53.85639,
        27.4907,
        "minsk-ledlife",
        True,
        "ledlife_origin_html_v1",
        _MSK,
    ),
    SeedArena(
        5,
        "Минск",
        "Ледовый дворец спорта Минской области",
        "Минск, ул. Притыцкого, 27",
        53.90757,
        27.48631,
        "ledovyy-dvorets-sporta-minskoy-oblasti",
        True,
        "ledby_html_v1",
        _MSK,
    ),
    SeedArena(
        6,
        "Минск",
        "Чижовка-арена",
        "Минск, ул. Ташкентская, 19",
        53.844534,
        27.628657,
        "chizhovka-arena",
        True,
        "chizhovka_html_v1",
        _MSK,
    ),
    SeedArena(
        7,
        "Минск",
        "ТЦ DiaMond city",
        "Минск, ул. Лещинского, 8",
        53.84966,
        27.433552,
        "tts-diamond-city",
        True,
        "diamond_html_v1",
        _MSK,
    ),
    SeedArena(
        8,
        "Минск",
        'Каток хк "Юность"',
        "Первомайская улица, 3, Минск, Минская область",
        53.90141,
        27.57375,
        "katok-khk-yunost",
        True,
        "junost_instagram_caption_v1",
        _MSK,
    ),
    SeedArena(
        115,
        "Минск",
        "Конькобежный стадион",
        "проспект Победителей, 111",
        53.93593,
        27.481638,
        "konkobezhnaya-arena",
        True,
        "minskarena_speed_oval_v1",
        _MSK,
    ),
    SeedArena(
        53,
        "Москва/МО",
        "ВТБ Арена (Академия спорта «Динамо»)",
        "ул. Юрия Никулина, 3",
        None,
        None,
        "vtb-arena-akademiya-sporta-dinamo",
        True,
        "vtbarena_qtickets_v1",
        _MOW,
    ),
    SeedArena(
        58,
        "Москва/МО",
        "Ледовый дворец «Сокольники»",
        "улица Сокольнический Вал, 1Б",
        55.7928941,
        37.6714915,
        "ledovyy-dvorets-sokolniki",
        True,
        "ldsokolniki_html_v1",
        _MOW,
    ),
    SeedArena(
        97,
        "Санкт-Петербург/ЛО",
        "СК «Юбилейный»",
        "проспект Добролюбова, 18",
        59.9498865,
        30.2910466,
        "sk-yubileynyy",
        True,
        "yubileyny_afisha_html_v1",
        _MOW,
    ),
    SeedArena(
        99,
        "Санкт-Петербург/ЛО",
        "ЛД «Гранд Каньон Айс»",
        "Суздальский проспект 29",
        60.0605072,
        30.3384229,
        "ld-grand-kanon-ays",
        True,
        "grandice_json_v1",
        _MOW,
    ),
    SeedArena(
        100,
        "Санкт-Петербург/ЛО",
        "Ледовый комплекс «Шанс Арена»",
        "ул. Грибалёвой 9к2",
        59.9845612,
        30.355413,
        "ledovyy-kompleks-shans-arena",
        True,
        "shansarena_html_v1",
        _MOW,
    ),
    SeedArena(
        101,
        "Санкт-Петербург/ЛО",
        "Ледовая арена Озерки",
        "Большая Озерная ул., 56",
        60.0374577,
        30.3059034,
        "ledovaya-arena-ozerki",
        True,
        "ozerki_gcal_v1",
        _MOW,
    ),
    SeedArena(
        105,
        "Санкт-Петербург/ЛО",
        "Ледовый дворец",
        "пр. Пятилеток, 1",
        None,
        None,
        "ledovyy-dvorets",
        True,
        "ledovyydvorets_html_v1",
        _MOW,
    ),
    SeedArena(
        110,
        "Санкт-Петербург/ЛО",
        "Ледовая арена «Купчино»",
        "ул. Димитрова, 3А",
        59.8441306,
        30.3776715,
        "ledovaya-arena-kupchino",
        True,
        "kupchinoarena_html_v1",
        _MOW,
    ),
    SeedArena(
        111,
        "Санкт-Петербург/ЛО",
        "Ледовая арена Бугры",
        "Шоссейная улица 42",
        60.0606356,
        30.3855117,
        "ledovaya-arena-bugry",
        True,
        "bugryarena_html_v1",
        _MOW,
    ),
    SeedArena(
        173,
        "Санкт-Петербург/ЛО",
        "Ледовая арена Динамо-Юниор",
        "улица Фаворского, 7",
        60.002463,
        30.376567,
        "ledovaya-arena-dinamo-yunior",
        True,
        "dinamoyunior_html_v1",
        _MOW,
    ),
    SeedArena(
        174,
        "Санкт-Петербург/ЛО",
        "Центр ледовых видов спорта Парнас",
        "6-й Верхний переулок, 12Б",
        60.068212,
        30.344406,
        "tsentr-ledovykh-vidov-sporta-parnas",
        True,
        "parnasarena_text_v1",
        _MOW,
    ),
    SeedArena(
        185,
        "Санкт-Петербург/ЛО",
        "Ижорец",
        "Колпинский район, посёлок Металлострой, Пушкинская улица, 3А",
        59.806151,
        30.579245,
        "izhorets",
        True,
        "izhorets_html_v1",
        _MOW,
    ),
    SeedArena(
        187,
        "Санкт-Петербург/ЛО",
        "Ледовая арена Магнит",
        "Магнитогорская улица, 51В",
        59.937716,
        30.433026,
        "ledovaya-arena-magnit",
        True,
        "magnitarena_html_v1",
        _MOW,
    ),
    SeedArena(
        192,
        "Санкт-Петербург/ЛО",
        "Балтик Арена",
        "Василеостровский намыв",
        59.953744,
        30.19477,
        "baltik-arena",
        True,
        "balticarena_html_v1",
        _MOW,
    ),
    SeedArena(
        193,
        "Санкт-Петербург/ЛО",
        "Айсбург Арена",
        "Парашютная улица, 11",
        60.015243,
        30.274351,
        "aysburg-arena",
        True,
        "iceburgarena_yclients_v1",
        _MOW,
    ),
    SeedArena(
        196,
        "Санкт-Петербург/ЛО",
        "Шуваловский лёд",
        "улица Лидии Зверевой, 8",
        60.041656,
        30.250138,
        "shuvalovskiy-led",
        True,
        "shuvalovskyled_html_v1",
        _MOW,
    ),
]


def apply_capital_arenas(session: Session, *, verbose: bool = True) -> None:
    """Insert Minsk / Moscow / St. Petersburg cities, arenas, and profiles. Does not commit."""
    apply_arena_seed(session, CAPITAL_CITIES, ARENAS, verbose=verbose)
